### ISSUE TITLE
Redundanzen in Compose

### ISSUE THREAD

**Issue by C0d3GGz** [LeylaGitHub/MoCoSS2023_Notzon_vonScheidt_Issa#5]
Mir ist aufgefallen, dass sie viele Redundanzen in Ihrem Compose code haben, bpsw. folgende Struktur kommt oft vor:

```
Surface(
  Modifier
    .width(70.dp)
    .height(70.dp),
  border = BorderStroke(2.dp, Color.Black),
  shape = CircleShape,
  color = Color.Transparent
) {
  Text(
    "Körper",
    Modifier
      .padding(10.dp)
      .align(Alignment.CenterVertically),
    textAlign = TextAlign.Center,
    fontSize = 15.sp,
    fontWeight = Bold
  )
}
```

Versuchen Sie ein einzelnes composables zu definieren, dass dann einen "name" und andere Parameter entgegen nimmt um diese Redundanzen zu vermeiden.

**Comment by Alessa-v-Scheidt** [comment]
Bearbeitet in Pull Request https://github.com/LeylaGitHub/MoCoSS2023_Notzon_vonScheidt_Issa/pull/7
